### ISSUE TITLE
.png transparency files

### ISSUE THREAD

**Issue by jaminellis** [cruncher/grunt-rem-to-px#2]
Very useful grunt task for those of us still having to support IE<9. Is there a script to generate the png files that replace the rgba backgrounds with transparent pngs?

**Comment by stephband** [comment]
No, but you'll find a bunch of them here:
https://github.com/stephband/bolt/tree/master/images/bg

I'm afraid I finished with IE8 last year, so I'm not maintaining this grunt
task.


––––––––––––
http://sound.io
http://cruncher.ch
http://stephen.band

**Comment by jaminellis** [comment]
Many thanks Steph!
